### ISSUE TITLE
Cannot install Dropbox plugin 

### ISSUE THREAD

**Issue by leventehollo** [raguay/DropboxConnect#3]
This is the popup error message I got after I tried to install the plugin

> Plugin 'DropboxConnect' failed to load.
> 
> Traceback (most recent call last):
>   File "fman/impl/plugins/plugin.py", line 133, in load
>   File "fman/impl/plugins/plugin.py", line 148, in _load
>   File "fman/impl/plugins/plugin.py", line 163, in _load_classes
>   File "fman/impl/plugins/plugin.py", line 214, in _load_packages
>   File "importlib/__init__.py", line 126, in import_module
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/home/lev/.config/fman/Plugins/Third-party/DropboxConnect/dropboxconnect/__init__.py", line 15, in <module>
>     import dropbox
>   File "/home/lev/.config/fman/Plugins/Third-party/DropboxConnect/dropbox-sdk-python/dropbox/__init__.py", line 3, in <module>
>     from .dropbox import __version__, Dropbox, DropboxTeam, create_session  # noqa: F401
>   File "/home/lev/.config/fman/Plugins/Third-party/DropboxConnect/dropbox-sdk-python/dropbox/dropbox.py", line 35, in <module>
>     from .session import (
>   File "/home/lev/.config/fman/Plugins/Third-party/DropboxConnect/dropbox-sdk-python/dropbox/session.py", line 1, in <module>
>     import pkg_resources
> ImportError: No module named 'pkg_resources'

**Comment by raguay** [comment]
Install the latest version. The package 'pkg_resources` requirement has been fixed and should now work on Linux as well as macOS. I can't test right now on Linux or Windows, but I think it should work.
